
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes: 
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: dockerfiles/php/Dockerfile
    volumes: 
      - ./app:/var/www/html
    depends_on:
      - database
    networks:
      - backend

  database:
    image: timescale/timescaledb:latest-pg17
    restart: unless-stopped
    ports:   
      - 5431:5432             
    volumes: 
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pg_data:
  db_data:
