services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes: 
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: dockerfiles/php/Dockerfile
    volumes: 
      - ./app:/var/www/html
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - backend
      - database

  database:
    image: postgres:17
    restart: unless-stopped
    ports:   
      - 5431:5432             
    volumes: 
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - database

  pgadmin:
    image: dpage/pgadmin4:9
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - database

volumes:
  pg_data:
  db_data:

networks:
  backend:
    driver: bridge
  database:
    driver: bridge
